<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="custom-product-gallery">
    <?php
        $galleryImages = json_decode($block->getGalleryImagesJson(), true);
        if (!empty($galleryImages)) {
            foreach ($galleryImages as $image) {
                echo '<img src="' . $image['img'] . '" alt="' . $image['caption'] . '">';
            }
        }
    ?>   
</div>

<script type="text/x-magento-init">
{
   "*": {
       "custom-gallery": {}
   }
}
</script>